spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  profiles :
    include: oauth

  jpa :
    show_sql : true
    hibernate :
      ddl-auto : create

security.jwt.token:
  secret-key: ${JWT_SECRET_KEY}
  expire-length : ${JWT_VALIDITY}