name: PR Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: properties 파일 복사
        run: |
          echo "${{ secrets.APPLICATION_TEST_SECRET_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Test Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          title: Test Coverage Report
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GIT_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50